apiVersion: apps/v1
kind: Deployment
metadata:
  name: chart-blue-nginx
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: demoApp
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}"
          ports:
            - containerPort: 3030
  selector:
    matchLabels:
      app: demoApp
