apiVersion: v1
kind: Service
metadata:
  name: chart-blue-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: chart-blue-nginx
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
